image: manojmanivannan18/python-hellomaven:build

before_script:
  - source ~/.bashrc

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

services:
  - name: docker:18-dind
    alias: docker

cache:
 paths:
   - target/
   - .m2/


stages:
  - test
  - build
  - release


.BuildPackage:
  stage: build
  artifacts:
    paths:
      - target/generated-sources/liveisstracker/dist/
      - .m2/current_branch_snapshot
    expire_in: 1 week

buildTagged:
  extends: .BuildPackage
  script:
      - /bin/bash .m2/gitlab_build.sh --branch ${CI_COMMIT_REF_NAME} --taggedBuild true --get_version > .m2/current_branch_snapshot
      - /bin/bash .m2/gitlab_build.sh --branch ${CI_COMMIT_REF_NAME} --taggedBuild true
  only:
      - tags


buildFeatureOrBugfix:
  extends: .BuildPackage
  script:
      - /bin/bash .m2/gitlab_build.sh --branch ${CI_COMMIT_REF_NAME} --get_version > .m2/current_branch_snapshot
      - /bin/bash .m2/gitlab_build.sh --branch ${CI_COMMIT_REF_NAME}
  except:
      - tags
      - develop

buildDevelop:
  extends: .BuildPackage
  script:
      - /bin/bash .m2/gitlab_build.sh --branch ${CI_DEFAULT_BRANCH} --get_version > .m2/current_branch_snapshot
      - /bin/bash .m2/gitlab_build.sh --branch ${CI_DEFAULT_BRANCH}
  only:
      - develop

release-pip-tag:
  stage: release
  artifacts:
    paths:
      - target/generated-sources/liveisstracker/dist/
      - .m2/current_branch_snapshot
  script:
      - pip3 install -U twine
      - cd target/generated-sources/liveisstracker
      - python3 setup.py sdist bdist_wheel && find dist/ -type f -not -name "*${CI_COMMIT_TAG}*" -exec rm -v {} \;
      - twine upload dist/*
  only:
      - tags
$(.m2/gitlab_build.sh --get_version)-$(date +%Y-%m-%d-%H-%M)


release-pip-featureORbugfix:
  stage: release
  artifacts:
    paths:
      - target/generated-sources/liveisstracker/dist/
      - .m2/current_branch_snapshot
  script:
      - pip3 install -U twine
      - cd target/generated-sources/liveisstracker
      - sed "s#version=.*#version=\"$(../../../.m2/gitlab_build.sh --get_version)-$(date +%Y-%m-%d-%H-%M)\"#g" setup.py 
      - python3 setup.py sdist bdist_wheel && find dist/ -type f -not -name "*$(../../../.m2/gitlab_build.sh --get_version)-$(date +%Y-%m-%d-%H-%M)*" -exec rm -v {} \;
      - twine upload dist/*
  except:
      - tags
      - develop

test:
    image: manojmanivannan18/python-hellomaven:pytest
    stage: test
    before_script:
      - source ~/.bashrc    
    script:
      - make run_python_tests TEST_USER=ROOT
    after_script:
      - docker stop python_app && docker rm python_app
    artifacts:
      when: always
      reports:
        junit: target/generated-sources/liveisstracker/liveisstracker/report.xml

