version: "3.1"
services:
  app:
    image: registry.gitlab
    volumes:
      - ./target/generated-sources/liveisstracker/liveisstracker:/home/manoj/liveisstracker

    depends_on: 
        - db
          # condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - MAPBOX_TOKEN=/run/secrets/mapbox_token
    secrets:
      - mapbox_token
    links:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    restart: on-failure:5
    ports:
      - "8501:8501"

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./target/generated-sources/db:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_ROOT_PASSWORD


volumes:
  mysqldb:
    driver: local

secrets:
   mapbox_token:
     file: map_secret.txt
