version: "2.1"
services:
  app:
    image: gitlab_registry
    volumes:
      - ./target/generated-sources/liveisstracker/liveisstracker:/home/manoj/liveisstracker

    depends_on:
        db:
            condition: service_healthy
    links:
      - db
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./target/generated-sources/db:/docker-entrypoint-initdb.d/:ro
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 10s
        retries: 10

volumes:
  mysqldb:
    driver: local

