CREATE DATABASE IF NOT EXISTS dev;
USE dev;
CREATE TABLE IF NOT EXISTS location (id INT(6) AUTO_INCREMENT PRIMARY KEY, lat VARCHAR(20), lon VARCHAR(20), datetime_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP, datetime_id INT(10));
