name: CI/CD

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - "*"

jobs:
    pytest_build:
        runs-on: ubuntu-latest
        permissions: write-all
        container:
            image: manojmanivannan18/python-hellomaven:pytest
            volumes:
                - ${{ github.workspace }}:/work
        env:
          MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
          MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: run-test-build
              shell: bash
              run: |
                echo "--This is running in Docker image--"
                cd /work && source .bashrc 
                make run_python_tests TEST_USER=root
                pip3 install -U twine
                /bin/bash .m2/gitlab_build.sh --branch ${{ github.ref }} --git_repo_url "ghcr.io/${{ github.repository }}"







  # build:
  #   name: Build and Release
  #   runs-on: ubuntu-latest
  #   services:
  #     docker:
  #       image: docker:18-dind
  #       options: --privileged
  #   steps:
  #     - name: Cache maven
  #       uses: actions/cache@v3
  #       with:
  #         path: .m2/
  #         key: v1-npm-deps-${{ hashFiles('**/settings.xml') }}
  #         restore-keys: v1-npm-deps-
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Build and Release tagged
  #       if: startsWith(github.ref, 'refs/tags/')
  #       run: |
  #         sed -i "0,/<version>.*/s/<version>.*/<version>${{ github.ref_name }}<\/version>/g" pom.xml
  #         /bin/bash .m2/gitlab_build.sh --branch ${{ github.ref_name }} --taggedBuild true --get_version > .m2/current_branch_snapshot
  #         /bin/bash .m2/gitlab_build.sh --branch ${{ github.ref_name }} --taggedBuild true
  #         twine upload target/generated-sources/liveisstracker/dist/*
  #     - name: Build and Release branches
  #       if: startsWith(github.ref, 'refs/heads/') && github.ref != 'refs/heads/develop'
  #       run: |
  #         /bin/bash .m2/gitlab_build.sh --branch ${{ github.ref_name }} --get_version > .m2/current_branch_snapshot
  #         /bin/bash .m2/gitlab_build.sh --branch ${{ github.ref_name }}
  #     - name: Build and Release develop
  #       if: github.ref == 'refs/heads/develop'
  #       run: |
  #         /bin/bash .m2/gitlab_build.sh --branch ${CI_DEFAULT_BRANCH} --get_version > .m2/current_branch_snapshot
  #         /bin/bash .m2/gitlab_build.sh --branch ${CI_DEFAULT_BRANCH}
